### ISSUE TITLE
Can remove commented out code

### ISSUE THREAD

**Issue by Jbarget** [FAC10/week5-SoFLY-newsfeedAPI#61]
https://github.com/FAC10/week5-SoFLY-newsfeedAPI/blob/master/test/tests.js#L4
https://github.com/FAC10/week5-SoFLY-newsfeedAPI/blob/f05708b704ef9e40a0457a7e4ff1b77bc141b3dd/test/tests.js#L13

**Comment by RhodesPeter** [comment]
I would remove this too as it shows up in your console:

![screen shot 2017-03-24 at 10 41 54](https://cloud.githubusercontent.com/assets/18164707/24290859/8519e018-107e-11e7-94b3-447b681f9ced.png)

(scripts.js, line 17)

**Comment by finnhodgkin** [comment]
@Jbarget Fixed - thanks!
