### ISSUE TITLE
Make the two API requests simultaneously

### ISSUE THREAD

**Issue by msachi** [FAC10/week5-SoFLY-newsfeedAPI#67]
https://github.com/FAC10/week5-SoFLY-newsfeedAPI/blob/master/src/handler.js#L49-L64

At the moment it appears that your NYT API is only called once the Guardian API response comes back. It would be more efficient to call both APIs simultaneously, and respond to client once you've got both responses. You could use the parallel function for this.

**Comment by yvonne-liu** [comment]
@finnhodgkin 😏
