### ISSUE TITLE
module.exports always defined in the same place in a file

### ISSUE THREAD

**Issue by Jbarget** [FAC10/week5-SoFLY-newsfeedAPI#68]
In terms of readability having the definition of what is exported out of the file should be easy to find.
I would find it a lot easier if it was in the same place for every file across the project, either at the top or at the bottom

https://github.com/FAC10/week5-SoFLY-newsfeedAPI/blob/master/test/backend/route-tests.js#L54
https://github.com/FAC10/week5-SoFLY-newsfeedAPI/blob/master/test/backend/guardiantestobj.js#L209
https://github.com/FAC10/week5-SoFLY-newsfeedAPI/blob/master/test/backend/route-tests.js#L9

**Comment by samatar26** [comment]
Thanks, makes sense, I guess it relates to setting out conventions at the start of the project

**Comment by Jbarget** [comment]
👍
