### ISSUE TITLE
Set group conventions at the start of the project and document in your readme

### ISSUE THREAD

**Issue by Jbarget** [FAC10/week5-SoFLY-newsfeedAPI#70]
A few of the issues i've created all link to the same idea that you're working as a team with different preferences on how to write code. Its good to set some guidelines for the team at the start of the project for everyone to work with. Eg:

- indentation
- casing
- module.exports position
- im sure theres some others but cant think of any more right now

**Comment by finnhodgkin** [comment]
@Jbarget 
We ran into casing problems a loot during this project. If we'd had a discussion like the above it could've us saved a bunch of time... Definitely something for the future :+1:

**Comment by Jbarget** [comment]
noice 👍
