### ISSUE TITLE
Don't need to export each test

### ISSUE THREAD

**Issue by samhstn** [FAC10/week5-SoFLY-newsfeedAPI#72]
Instead of requiring each test and invoking it, you can just require in the file, that way you don't need to wrap each file test and `module.export` it

I find this pattern easier to read

**Comment by samatar26** [comment]
Seemed to have worked :+1: , but how can you require a file without exporting it? @shouston3

**Comment by samhstn** [comment]
How can you require a file without exporting it?

Just don't have a `module.exports` in the file you are requiring
