### ISSUE TITLE
example.env file

### ISSUE THREAD

**Issue by msachi** [FAC10/week5-SoFLY-newsfeedAPI#73]
I'm guessing this should be removed

**Comment by yvonne-liu** [comment]
Relates to #54 but we will specify its use 😊  thanks! @Samatar26

**Comment by samatar26** [comment]
Is it not good practice to have one, to show other developers that they will require one?  @msachi

**Comment by msachi** [comment]
@Samatar26 I think if you want to do that you could have installation instructions in your README, that specify what developers will need to do to run your project locally.

**Comment by msachi** [comment]
(Including commands to run the server, run the tests etc.)

**Comment by samatar26** [comment]
@msachi Fixed
