### ISSUE TITLE
heya

### ISSUE THREAD

**Issue by Jbarget** [FAC10/week5-SoFLY-newsfeedAPI#94]
heya, you want to be letting the person who opened the issue know that you have fixed the issue, a comment or just to make sure you can @ them n they will get a notification in the top right of github:

![screen shot 2017-03-24 at 12 39 19](https://cloud.githubusercontent.com/assets/11725595/24294553/f04e5cb4-108e-11e7-9468-86935fe18813.png)

**Comment by yvonne-liu** [comment]
Heya 👋

**Comment by Jbarget** [comment]
whoop whoop 🎉
